[versions]
agp = "8.7.3"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
composeBom = "2024.04.01"
retrofit = "2.11.0"
okhttp3 = "4.9.3"
daggerHilt = "2.56.1"
hiltNavigation = "1.2.0"
coil = "3.1.0"
nav = "2.8.9"
serialization = "1.7.3"
serializationPlugin = "2.0.21"
kotlinParcelize = "1.8.10"
paging = "3.3.6"
coroutines = "1.10.2"
datastore = "1.1.7"
protobuf = "3.25.1"
protobufPlugin = "0.9.4"
room = "2.8.2"
secretsGradlePlugin = "2.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "daggerHilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
#paging
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
#retrofit
squareup-retrofit = {group="com.squareup.retrofit2", name="retrofit", version.ref = "retrofit"}
squareup-gson = {group="com.squareup.retrofit2", name= "converter-gson", version.ref="retrofit"}
#okhttp
squareup-okhttp3 = {group="com.squareup.okhttp3", name="okhttp", version.ref="okhttp3"}
squareup-okhttp3-interceptor = {group="com.squareup.okhttp3", name="logging-interceptor", version.ref="okhttp3"}
#DaggerHilt
dagger-hilt = {group="com.google.dagger", name="hilt-android", version.ref="daggerHilt"}
dagger-hilt-compiler = {group="com.google.dagger", name="hilt-android-compiler", version.ref="daggerHilt"}
hilt-navigation-compose = {group="androidx.hilt", name="hilt-navigation-compose", version.ref="hiltNavigation"}
#coil
coil-compose = {group="io.coil-kt.coil3", name="coil-compose", version.ref = "coil"}
coil-network = {group="io.coil-kt.coil3", name="coil-network-okhttp", version.ref = "coil"}
compose-icons-extended = {group = "androidx.compose.material", name = "material-icons-extended"}
data-store = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
protobuf-gradle-plugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobufPlugin" }
#room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
#secrets-gradle-plugin
secrets-gradle = {group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version.ref="secretsGradlePlugin"}

#test Coroutine
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
devtools-ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
dagger-hilt-plugin = {id = "dagger.hilt.android.plugin"}
protobuf-plugin = {id = "com.google.protobuf", version.ref = "protobufPlugin"}
plugin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlinParcelize"  }
room-plugin = { id = "androidx.room", version.ref = "room" }
secrets-gradle-plugin = {id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin"}



